import json
import urllib2
import re

"""eisagwgh hmeromhnias klhrwshs apo ton xrhsth"""
date=raw_input("Dwse hmeromhnia klhrwshs sthn morfh dd-MM-yyyy:")

"""apothhkeush apotelesmatwn klhrwshs"""
response = urllib2.urlopen('http://applications.opap.gr/DrawsRestServices/kino/drawDate/'+date+'.json')
data=response.read()
newdata=re.findall('\d+', data)

"""emfanish plhthous emfanisewn kathe arithmou"""
print "1:",newdata.count('1')
print "2:",newdata.count('2')
print "3:",newdata.count('3')
print "4:",newdata.count('4')
print "5:",newdata.count('5')
print "6:",newdata.count('6')
print "7:",newdata.count('7')
print "8:",newdata.count('8')
print "9:",newdata.count('9')
print "10:",newdata.count('10')
print "11:",newdata.count('11')
print "12:",newdata.count('12')
print "13:",newdata.count('13')
print "14:",newdata.count('14')
print "15:",newdata.count('15')
print "16:",newdata.count('16')
print "17:",newdata.count('17')
print "18:",newdata.count('18')
print "19:",newdata.count('19')
print "20:",newdata.count('20')
print "21:",newdata.count('21')
print "22:",newdata.count('22')
print "23:",newdata.count('23')
print "24:",newdata.count('24')
print "25:",newdata.count('25')
print "26:",newdata.count('26')
print "27:",newdata.count('27')
print "28:",newdata.count('28')
print "29:",newdata.count('29')
print "30:",newdata.count('30')
print "31:",newdata.count('31')
print "32:",newdata.count('32')
print "33:",newdata.count('33')
print "34:",newdata.count('34')
print "35:",newdata.count('35')
print "36:",newdata.count('36')
print "37:",newdata.count('37')
print "38:",newdata.count('38')
print "39:",newdata.count('39')
print "40:",newdata.count('40')
print "41:",newdata.count('41')
print "42:",newdata.count('42')
print "43:",newdata.count('43')
print "44:",newdata.count('44')
print "45:",newdata.count('45')
print "46:",newdata.count('46')
print "47:",newdata.count('47')
print "48:",newdata.count('48')
print "49:",newdata.count('49')
print "50:",newdata.count('50')
print "51:",newdata.count('51')
print "52:",newdata.count('52')
print "53:",newdata.count('53')
print "54:",newdata.count('54')
print "55:",newdata.count('55')
print "56:",newdata.count('56')
print "57:",newdata.count('57')
print "58:",newdata.count('58')
print "59:",newdata.count('59')
print "60:",newdata.count('60')
print "61:",newdata.count('61')
print "62:",newdata.count('62')
print "63:",newdata.count('63')
print "64:",newdata.count('64')
print "65:",newdata.count('65')
print "66:",newdata.count('66')
print "67:",newdata.count('67')
print "68:",newdata.count('68')
print "69:",newdata.count('69')
print "70:",newdata.count('70')
print "71:",newdata.count('71')
print "72:",newdata.count('72')
print "73:",newdata.count('73')
print "74:",newdata.count('74')
print "75:",newdata.count('75')
print "76:",newdata.count('76')
print "77:",newdata.count('77')
print "78:",newdata.count('78')
print "79:",newdata.count('79')
print "80:",newdata.count('80')
